platform :ios, "7.0"

pod 'AFNetworking', '2.3.0'
pod 'CocoaLumberjack', '1.6'
pod 'UIColor-Utilities', '1.0.1'
pod 'TSMessages', '0.9.9'
pod 'NSDate-Extensions', '0.0.1'
pod 'BlocksKit', '2.2.3'
pod 'SVProgressHUD'
